# 190031920

# A Nikhil Reddy

# DS Practical 1

In [1]:
import numpy as np
import pandas as pd

In [2]:
a1=[10,15,17,26]
a2=[12,11,21,24]
ar1=np.array(a1)
ar2=np.array(a2)
sum_array=ar1+ar2
print(sum_array)

[22 26 38 50]


In [3]:
print(3*sum_array) 

[ 66  78 114 150]


In [4]:
print(np.sum(sum_array))

136


In [5]:
sum_array[sum_array!=26]

array([22, 38, 50])

In [6]:
np.logical_and(sum_array>20,sum_array<50) 

array([ True,  True,  True, False])

In [7]:
np.logical_or(sum_array>20,sum_array<50)



array([ True,  True,  True,  True])

In [8]:
a1=[1,3,5,7]
a2=[2,45,8,2]
ar1=np.array(a1)
ar2=np.array(a2)
print(ar1[1:])
print(ar1[:3])

[3 5 7]
[1 3 5]


In [9]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 2])
print(arr.shape)

[2 3 4 5]
[7 8 9]
[3 8]
(2, 5)


In [10]:
test_score=np.array([[83,71,57,63],[54,68,81,45]])
passing_score=test_score>60
passing_score

array([[ True,  True, False,  True],
       [False,  True,  True, False]])

In [11]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
#Sum of 2-d Array and multiply with 3
a1=np.array([[1,32,5],[1,53,6],[2,52,5]])
a2=np.array([[63,6,4],[8,9,4],[7,4,7]])
sum=a1+a2
sum
print(sum)
mlt=sum*3
mlt
#Slicing of 2 D Array
import numpy as np
import pandas as pd
a1=np.array([[1,32,5],[1,53,6],[2,52,5]])
a2=np.array([[63,6,4],[8,9,4],[7,4,7]])
print(a1[1,1:3])
print(a1[0,1:4])

[[64 38  9]
 [ 9 62 10]
 [ 9 56 12]]
[53  6]
[32  5]


In [13]:
ar1=np.array([[1,2,3],[4,5,6]])
ar2=np.array([[1,2,3],[4,5,6]])
sum_array=ar1+ar2
print(sum_array)

[[ 2  4  6]
 [ 8 10 12]]


In [14]:
#logical and
np.logical_and(sum_array>20,sum_array<50)

array([[False, False, False],
       [False, False, False]])

In [15]:
#logical or
np.logical_or(sum_array>20,sum_array<50) 


array([[ True,  True,  True],
       [ True,  True,  True]])

In [16]:
#logical not
np.logical_not(sum_array>20,sum_array<50) 


array([[ True,  True,  True],
       [ True,  True,  True]])

In [17]:
#slicing
print(sum_array[1,1:4])

[10 12]


In [18]:
#boolean
print(10 > 9)
print(10 == 9)
print(10 < 9)

True
False
False


In [19]:
a=np.array([[73,94,44,76,62,10,86,74],
          [86,4,9,87,31,11,33,31],
          [77,40,72,54,20,87,91,51],
          [84,87,34,29,78,26,10,93],
          [38,20,77,27,89,51,71,84],
          [70,11,33,55,66,92,97,26],
          [44,44,69,14,20,83,61,27],
          [42,23,33,41,8,4,93,8]])
a.reshape(4,4,4)

array([[[73, 94, 44, 76],
        [62, 10, 86, 74],
        [86,  4,  9, 87],
        [31, 11, 33, 31]],

       [[77, 40, 72, 54],
        [20, 87, 91, 51],
        [84, 87, 34, 29],
        [78, 26, 10, 93]],

       [[38, 20, 77, 27],
        [89, 51, 71, 84],
        [70, 11, 33, 55],
        [66, 92, 97, 26]],

       [[44, 44, 69, 14],
        [20, 83, 61, 27],
        [42, 23, 33, 41],
        [ 8,  4, 93,  8]]])

In [20]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [21]:
a=np.array([[0,1],[2,3]])
np.resize(a,(2,3))

array([[0, 1, 2],
       [3, 0, 1]])

In [22]:
x = np.arange(8).reshape(2, 2, 2)
np.hsplit(x, 2)

[array([[[0, 1]],
 
        [[4, 5]]]),
 array([[[2, 3]],
 
        [[6, 7]]])]

In [23]:
arr = np.arange(12).reshape((3, 4))
condition = np.mod(arr, 3)==0
np.extract(condition, arr)

array([0, 3, 6, 9])

In [24]:
#specify values of each columns
df=pd.DataFrame(
    {"a":[4,5,6],
     "b":[7,8,9],
     "c":[10,11,12]},
    index=[1,2,3]
)
df

a  b   c
1  4  7  10
2  5  8  11
3  6  9  12

In [25]:
#specify values of each rows
df=pd.DataFrame(
    [[4,7,10],
     [5,8,11],
     [6,9,12],],
    index=[1,2,3],
     columns=['a','b','c']
)
df

a  b   c
1  4  7  10
2  5  8  11
3  6  9  12

In [26]:
df=pd.DataFrame(
    {"a":[4,5,6],
     "b":[7,8,9],
     "c":[10,11,12]},
     index=pd.MultiIndex.from_tuples(
         [('d',1),('d',2),('e',3)],
         names=['n','v']
     ))
df

a  b   c
n v          
d 1  4  7  10
  2  5  8  11
e 3  6  9  12

In [27]:
import statistics

In [28]:
Dataset=pd.read_csv('ds-lab1-cvs.csv')
Dataset

gender NationalITy PlaceofBirth       StageID GradeID SectionID  \
0        M          KW       KuwaIT    lowerlevel    G-04         A   
1        M          KW       KuwaIT    lowerlevel    G-04         A   
2        M          KW       KuwaIT    lowerlevel    G-04         A   
3        M          KW       KuwaIT    lowerlevel    G-04         A   
4        M          KW       KuwaIT    lowerlevel    G-04         A   
..     ...         ...          ...           ...     ...       ...   
475      F      Jordan       Jordan  MiddleSchool    G-08         A   
476      F      Jordan       Jordan  MiddleSchool    G-08         A   
477      F      Jordan       Jordan  MiddleSchool    G-08         A   
478      F      Jordan       Jordan  MiddleSchool    G-08         A   
479      F      Jordan       Jordan  MiddleSchool    G-08         A   

         Topic Semester Relation  raisedhands  VisITedResources  \
0           IT        F   Father           15                16   
1           IT        F   Father           20                20   
2           IT        F   Father           10                 7   
3           IT        F   Father           30                25   
4           IT        F   Father           40                50   
..         ...      ...      ...          ...               ...   
475  Chemistry        S   Father            5                 4   
476    Geology        F   Father           50                77   
477    Geology        S   Father           55                74   
478    History        F   Father           30                17   
479    History        S   Father           35                14   

     AnnouncementsView  Discussion ParentAnsweringSurvey  \
0                    2          20                   Yes   
1                    3          25                   Yes   
2                    0          30                    No   
3                    5          35                    No   
4                   12          50                    No   
..                 ...         ...                   ...   
475                  5           8                    No   
476                 14          28                    No   
477                 25          29                    No   
478                 14          57                    No   
479                 23          62                    No   

    ParentschoolSatisfaction StudentAbsenceDays Class  
0                       Good            Under-7     M  
1                       Good            Under-7     M  
2                        Bad            Above-7     L  
3                        Bad            Above-7     L  
4                        Bad            Above-7     M  
..                       ...                ...   ...  
475                      Bad            Above-7     L  
476                      Bad            Under-7     M  
477                      Bad            Under-7     M  
478                      Bad            Above-7     L  
479                      Bad            Above-7     L  

[480 rows x 17 columns]

In [29]:
Dataset.describe

<bound method NDFrame.describe of     gender NationalITy PlaceofBirth       StageID GradeID SectionID  \
0        M          KW       KuwaIT    lowerlevel    G-04         A   
1        M          KW       KuwaIT    lowerlevel    G-04         A   
2        M          KW       KuwaIT    lowerlevel    G-04         A   
3        M          KW       KuwaIT    lowerlevel    G-04         A   
4        M          KW       KuwaIT    lowerlevel    G-04         A   
..     ...         ...          ...           ...     ...       ...   
475      F      Jordan       Jordan  MiddleSchool    G-08         A   
476      F      Jordan       Jordan  MiddleSchool    G-08         A   
477      F      Jordan       Jordan  MiddleSchool    G-08         A   
478      F      Jordan       Jordan  MiddleSchool    G-08         A   
479      F      Jordan       Jordan  MiddleSchool    G-08         A   

         Topic Semester Relation  raisedhands  VisITedResources  \
0           IT        F   Father           15 

In [30]:
Dataset.mean

<bound method NDFrame._add_numeric_operations.<locals>.mean of     gender NationalITy PlaceofBirth       StageID GradeID SectionID  \
0        M          KW       KuwaIT    lowerlevel    G-04         A   
1        M          KW       KuwaIT    lowerlevel    G-04         A   
2        M          KW       KuwaIT    lowerlevel    G-04         A   
3        M          KW       KuwaIT    lowerlevel    G-04         A   
4        M          KW       KuwaIT    lowerlevel    G-04         A   
..     ...         ...          ...           ...     ...       ...   
475      F      Jordan       Jordan  MiddleSchool    G-08         A   
476      F      Jordan       Jordan  MiddleSchool    G-08         A   
477      F      Jordan       Jordan  MiddleSchool    G-08         A   
478      F      Jordan       Jordan  MiddleSchool    G-08         A   
479      F      Jordan       Jordan  MiddleSchool    G-08         A   

         Topic Semester Relation  raisedhands  VisITedResources  \
0           IT   

In [31]:
Dataset.median

<bound method NDFrame._add_numeric_operations.<locals>.median of     gender NationalITy PlaceofBirth       StageID GradeID SectionID  \
0        M          KW       KuwaIT    lowerlevel    G-04         A   
1        M          KW       KuwaIT    lowerlevel    G-04         A   
2        M          KW       KuwaIT    lowerlevel    G-04         A   
3        M          KW       KuwaIT    lowerlevel    G-04         A   
4        M          KW       KuwaIT    lowerlevel    G-04         A   
..     ...         ...          ...           ...     ...       ...   
475      F      Jordan       Jordan  MiddleSchool    G-08         A   
476      F      Jordan       Jordan  MiddleSchool    G-08         A   
477      F      Jordan       Jordan  MiddleSchool    G-08         A   
478      F      Jordan       Jordan  MiddleSchool    G-08         A   
479      F      Jordan       Jordan  MiddleSchool    G-08         A   

         Topic Semester Relation  raisedhands  VisITedResources  \
0           IT 

In [32]:
x=slice(3)
print(Dataset[x])

  gender NationalITy PlaceofBirth     StageID GradeID SectionID Topic  \
0      M          KW       KuwaIT  lowerlevel    G-04         A    IT   
1      M          KW       KuwaIT  lowerlevel    G-04         A    IT   
2      M          KW       KuwaIT  lowerlevel    G-04         A    IT   

  Semester Relation  raisedhands  VisITedResources  AnnouncementsView  \
0        F   Father           15                16                  2   
1        F   Father           20                20                  3   
2        F   Father           10                 7                  0   

   Discussion ParentAnsweringSurvey ParentschoolSatisfaction  \
0          20                   Yes                     Good   
1          25                   Yes                     Good   
2          30                    No                      Bad   

  StudentAbsenceDays Class  
0            Under-7     M  
1            Under-7     M  
2            Above-7     L  
